apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"frontend-service","namespace":"taskapp"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"frontend"}}}
  creationTimestamp: "2026-07-10T21:41:46Z"
  name: frontend-service
  namespace: taskapp
  resourceVersion: "363279"
  uid: 9c30bf92-c0dc-4461-af37-0df833204797
spec:
  clusterIP: 10.43.231.71
  clusterIPs:
  - 10.43.231.71
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
