apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"cert-manager.io/cluster-issuer":"letsencrypt-prod"},"name":"taskapp-ingress","namespace":"taskapp"},"spec":{"rules":[{"host":"taskapp.13.61.142.226.nip.io","http":{"paths":[{"backend":{"service":{"name":"backend","port":{"number":5000}}},"path":"/api","pathType":"Prefix"},{"backend":{"service":{"name":"frontend-service","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}],"tls":[{"hosts":["taskapp.13.61.142.226.nip.io"],"secretName":"taskapp-tls-cert"}]}}
    creationTimestamp: "2026-07-14T11:36:08Z"
    generation: 2
    name: taskapp-ingress
    namespace: taskapp
    resourceVersion: "565790"
    uid: 2bdc23fa-1a81-4a07-a69e-c120be7f560e
  spec:
    ingressClassName: traefik
    rules:
    - host: taskapp.13.61.142.226.nip.io
      http:
        paths:
        - backend:
            service:
              name: backend
              port:
                number: 5000
          path: /api
          pathType: Prefix
        - backend:
            service:
              name: frontend-service
              port:
                number: 80
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - taskapp.13.61.142.226.nip.io
      secretName: taskapp-tls-cert
  status:
    loadBalancer:
      ingress:
      - ip: 10.0.1.228
      - ip: 10.0.1.31
      - ip: 10.0.1.53
kind: List
metadata:
  resourceVersion: ""
