apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix-app
  labels:
    app: phoenix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phoenix
  template:
    metadata:
      labels:
        app: phoenix
    spec:
      containers:
      - name: phoenix-container
        image: nginx:latest # Standard web image to test our routing initially
        ports:
        - containerPort: 80
