[control_plane]
control-plane ansible_host=13.61.142.226 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[workers]
worker-0 ansible_host=13.60.70.208 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
worker-1 ansible_host=51.20.60.72 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[cluster:children]
control_plane
workers

[cluster:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
